// Portfolio Twin Schemas
export {
  PortfolioTwinSchema,
  CreatePortfolioTwinRequestSchema,
  UpdatePortfolioTwinRequestSchema,
  AddHoldingRequestSchema,
  UpdateHoldingRequestSchema,
  RebalanceRequestSchema,
  UpdatePerformanceRequestSchema,
  UpdateRiskMetricsRequestSchema,
  PortfolioTwinResponseSchema,
  PortfolioTwinListResponseSchema,
  type PortfolioTwin,
  type CreatePortfolioTwinRequest,
  type UpdatePortfolioTwinRequest,
  type AddHoldingRequest,
  type UpdateHoldingRequest,
  type RebalanceRequest,
  type UpdatePerformanceRequest,
  type UpdateRiskMetricsRequest,
  type PortfolioTwinResponse,
  type PortfolioTwinListResponse,
  // Enums
  PortfolioTypeSchema,
  PortfolioStatusSchema,
  HoldingSchema,
  CashSchema,
  PerformanceSchema,
  RiskMetricsSchema,
  AllocationSchema,
  ComplianceSchema,
  BenchmarkSchema,
  type Holding,
  type Cash,
  type Performance,
  type RiskMetrics,
  type Allocation,
  type Compliance,
  type Benchmark,
} from './portfolio-twin.schema.js';

// Investor Twin Schemas
export {
  InvestorTwinSchema,
  CreateInvestorTwinRequestSchema,
  UpdateInvestorTwinRequestSchema,
  UpdatePreferencesRequestSchema,
  UpdateKYCRequestSchema,
  LinkAccountRequestSchema,
  AddPortfolioRequestSchema,
  InvestorTwinResponseSchema,
  InvestorTwinListResponseSchema,
  type InvestorTwin,
  type CreateInvestorTwinRequest,
  type UpdateInvestorTwinRequest,
  type UpdatePreferencesRequest,
  type UpdateKYCRequest,
  type LinkAccountRequest,
  type AddPortfolioRequest,
  type InvestorTwinResponse,
  type InvestorTwinListResponse,
  // Enums
  InvestorTypeSchema,
  RiskRatingSchema,
  TimeHorizonSchema,
  LiquidityNeedsSchema,
  KYCStatusSchema,
  AMLCheckSchema,
  NameSchema,
  ProfileSchema,
  KYCSchema,
  PreferencesSchema,
  FinancialProfileSchema,
  ConnectedAccountSchema,
  ActivitySchema,
  PermissionsSchema,
  type Name,
  type Profile,
  type KYC,
  type Preferences,
  type FinancialProfile,
  type ConnectedAccount,
  type Activity,
  type Permissions,
} from './investor-twin.schema.js';

// Asset Twin Schemas
export {
  AssetTwinSchema,
  CreateAssetTwinRequestSchema,
  UpdateAssetTwinRequestSchema,
  UpdatePricingRequestSchema,
  AddNewsRequestSchema,
  AssetTwinResponseSchema,
  AssetTwinListResponseSchema,
  type AssetTwin,
  type CreateAssetTwinRequest,
  type UpdateAssetTwinRequest,
  type UpdatePricingRequest,
  type AddNewsRequest,
  type AssetTwinResponse,
  type AssetTwinListResponse,
  // Enums
  AssetClassSchema,
  TrendSchema,
  SentimentSchema,
  IslamicComplianceStatusSchema,
  AssetProfileSchema,
  PricingSchema,
  FundamentalsSchema,
  TechnicalSchema,
  TopHolderSchema,
  OwnershipSchema,
  IslamicComplianceSchema,
  NewsItemSchema,
  type AssetProfile,
  type Pricing,
  type Fundamentals,
  type Technical,
  type TopHolder,
  type Ownership,
  type IslamicCompliance,
  type NewsItem,
} from './asset-twin.schema.js';
