# Kubernetes Service for REZ-atlas-field-app
apiVersion: v1
kind: Service
metadata:
  name: REZ-atlas-field-app
  namespace: rez-merchant
  labels:
    app: REZ-atlas-field-app
    managed-by: rez-merchant
  annotations:
    description: "REZ-atlas-field-app service"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5191
      targetPort: http
      protocol: TCP
  selector:
    app: REZ-atlas-field-app
