apiVersion: v1
kind: Service
metadata:
  name: hotel-twinos-gateway
  namespace: hotel-os
  labels:
    app: hotel-twinos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: hotel-twinos
    component: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-guest-twin
  namespace: hotel-os
  labels:
    app: hotel-twinos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4201
      protocol: TCP
      name: http
  selector:
    app: hotel-twinos
    component: guest-twin
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-room-twin
  namespace: hotel-os
  labels:
    app: hotel-twinos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4202
      protocol: TCP
      name: http
  selector:
    app: hotel-twinos
    component: room-twin
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-property-twin
  namespace: hotel-os
  labels:
    app: hotel-twinos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4203
      protocol: TCP
      name: http
  selector:
    app: hotel-twinos
    component: property-twin
