import {
  Tenant,
  TenantStats,
  PlatformUser,
  UserStats,
  Module,
  TenantModule,
  BillingRecord,
  BillingStats,
  ApiKey,
  PlatformAnalytics,
  UsageTrend,
  DashboardStats,
} from '@/types';

// Generate realistic mock tenants
export const mockTenants: Tenant[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    slug: 'techcorp',
    domain: 'techcorp.example.com',
    logo: 'https://ui-avatars.com/api/?name=TC&background=3b82f6&color=fff',
    industry: 'Technology',
    status: 'active',
    plan: 'enterprise',
    modules: ['hr', 'payroll', 'performance', 'analytics', 'document'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-20T14:30:00Z',
    userCount: 450,
    adminEmail: 'admin@techcorp.com',
    adminName: 'Sarah Johnson',
    phone: '+1 555-0100',
    address: '123 Innovation Drive',
    city: 'San Francisco',
    country: 'USA',
    billingEmail: 'billing@techcorp.com',
    maxUsers: 500,
    apiCalls: 125000,
    storageUsed: 25000000000,
    monthlyRevenue: 9999,
  },
  {
    id: '2',
    name: 'HealthFirst Medical',
    slug: 'healthfirst',
    domain: 'healthfirst.example.com',
    logo: 'https://ui-avatars.com/api/?name=HF&background=22c55e&color=fff',
    industry: 'Healthcare',
    status: 'active',
    plan: 'professional',
    modules: ['hr', 'payroll', 'performance'],
    createdAt: '2024-03-22T09:00:00Z',
    updatedAt: '2024-06-18T11:15:00Z',
    userCount: 125,
    adminEmail: 'admin@healthfirst.com',
    adminName: 'Dr. Michael Chen',
    phone: '+1 555-0200',
    address: '456 Medical Center Blvd',
    city: 'Boston',
    country: 'USA',
    billingEmail: 'billing@healthfirst.com',
    maxUsers: 150,
    apiCalls: 45000,
    storageUsed: 8500000000,
    monthlyRevenue: 1999,
  },
  {
    id: '3',
    name: 'RetailMax Inc',
    slug: 'retailmax',
    domain: 'retailmax.example.com',
    logo: 'https://ui-avatars.com/api/?name=RM&background=f59e0b&color=fff',
    industry: 'Retail',
    status: 'active',
    plan: 'starter',
    modules: ['hr', 'payroll'],
    createdAt: '2024-05-10T08:00:00Z',
    updatedAt: '2024-06-15T16:45:00Z',
    userCount: 45,
    adminEmail: 'admin@retailmax.com',
    adminName: 'Emily Rodriguez',
    phone: '+1 555-0300',
    address: '789 Commerce Street',
    city: 'Chicago',
    country: 'USA',
    billingEmail: 'billing@retailmax.com',
    maxUsers: 50,
    apiCalls: 12000,
    storageUsed: 2100000000,
    monthlyRevenue: 499,
  },
  {
    id: '4',
    name: 'EduLearn Academy',
    slug: 'edulearn',
    domain: 'edulearn.example.com',
    logo: 'https://ui-avatars.com/api/?name=EL&background=8b5cf6&color=fff',
    industry: 'Education',
    status: 'pending',
    plan: 'professional',
    modules: ['hr', 'performance', 'analytics'],
    createdAt: '2024-06-25T12:00:00Z',
    updatedAt: '2024-06-28T09:30:00Z',
    userCount: 0,
    adminEmail: 'admin@edulearn.com',
    adminName: 'Prof. James Wilson',
    phone: '+1 555-0400',
    address: '321 University Ave',
    city: 'New York',
    country: 'USA',
    billingEmail: 'billing@edulearn.com',
    maxUsers: 200,
    apiCalls: 0,
    storageUsed: 0,
    monthlyRevenue: 0,
  },
  {
    id: '5',
    name: 'GreenEnergy Corp',
    slug: 'greenenergy',
    domain: 'greenenergy.example.com',
    logo: 'https://ui-avatars.com/api/?name=GE&background=10b981&color=fff',
    industry: 'Energy',
    status: 'active',
    plan: 'enterprise',
    modules: ['hr', 'payroll', 'performance', 'analytics', 'document', 'project'],
    createdAt: '2023-11-05T10:00:00Z',
    updatedAt: '2024-06-22T13:20:00Z',
    userCount: 780,
    adminEmail: 'admin@greenenergy.com',
    adminName: 'Lisa Thompson',
    phone: '+1 555-0500',
    address: '555 Renewable Way',
    city: 'Austin',
    country: 'USA',
    billingEmail: 'billing@greenenergy.com',
    maxUsers: 800,
    apiCalls: 210000,
    storageUsed: 45000000000,
    monthlyRevenue: 9999,
  },
  {
    id: '6',
    name: 'FinanceHub Partners',
    slug: 'financehub',
    domain: 'financehub.example.com',
    logo: 'https://ui-avatars.com/api/?name=FH&background=6366f1&color=fff',
    industry: 'Finance',
    status: 'suspended',
    plan: 'enterprise',
    modules: ['hr', 'payroll', 'performance', 'analytics', 'document', 'project'],
    createdAt: '2023-08-15T09:00:00Z',
    updatedAt: '2024-05-30T10:00:00Z',
    userCount: 320,
    adminEmail: 'admin@financehub.com',
    adminName: 'Robert Martinez',
    phone: '+1 555-0600',
    address: '888 Wall Street',
    city: 'New York',
    country: 'USA',
    billingEmail: 'billing@financehub.com',
    maxUsers: 400,
    apiCalls: 95000,
    storageUsed: 18000000000,
    monthlyRevenue: 9999,
  },
  {
    id: '7',
    name: 'MediaWorks Studio',
    slug: 'mediaworks',
    domain: 'mediaworks.example.com',
    logo: 'https://ui-avatars.com/api/?name=MW&background=ec4899&color=fff',
    industry: 'Media',
    status: 'active',
    plan: 'professional',
    modules: ['hr', 'payroll', 'project', 'document'],
    createdAt: '2024-02-28T11:00:00Z',
    updatedAt: '2024-06-19T15:10:00Z',
    userCount: 95,
    adminEmail: 'admin@mediaworks.com',
    adminName: 'Anna Lee',
    phone: '+1 555-0700',
    address: '999 Creative Lane',
    city: 'Los Angeles',
    country: 'USA',
    billingEmail: 'billing@mediaworks.com',
    maxUsers: 100,
    apiCalls: 38000,
    storageUsed: 9200000000,
    monthlyRevenue: 1999,
  },
  {
    id: '8',
    name: 'LogiTrans Logistics',
    slug: 'logitrans',
    domain: 'logitrans.example.com',
    logo: 'https://ui-avatars.com/api/?name=LT&background=14b8a6&color=fff',
    industry: 'Logistics',
    status: 'inactive',
    plan: 'starter',
    modules: ['hr'],
    createdAt: '2024-04-12T08:30:00Z',
    updatedAt: '2024-06-01T09:00:00Z',
    userCount: 28,
    adminEmail: 'admin@logitrans.com',
    adminName: 'David Kim',
    phone: '+1 555-0800',
    address: '444 Supply Chain Rd',
    city: 'Seattle',
    country: 'USA',
    billingEmail: 'billing@logitrans.com',
    maxUsers: 50,
    apiCalls: 5500,
    storageUsed: 1200000000,
    monthlyRevenue: 499,
  },
];

// Mock platform users
export const mockUsers: PlatformUser[] = [
  {
    id: '1',
    email: 'super@corpperks.com',
    name: 'Platform Super Admin',
    role: 'super_admin',
    status: 'active',
    lastLogin: '2024-06-29T08:30:00Z',
    createdAt: '2023-01-01T00:00:00Z',
    permissions: ['all'],
  },
  {
    id: '2',
    email: 'admin@corpperks.com',
    name: 'Platform Admin',
    role: 'admin',
    status: 'active',
    lastLogin: '2024-06-28T14:20:00Z',
    createdAt: '2023-06-15T10:00:00Z',
    permissions: ['tenants:read', 'tenants:write', 'users:read', 'billing:read'],
  },
  {
    id: '3',
    email: 'support@corpperks.com',
    name: 'Support Agent',
    role: 'support',
    status: 'active',
    lastLogin: '2024-06-29T09:15:00Z',
    createdAt: '2024-01-10T08:00:00Z',
    permissions: ['tenants:read', 'users:read'],
  },
  {
    id: '4',
    email: 'sarah@techcorp.com',
    name: 'Sarah Johnson',
    role: 'admin',
    tenantId: '1',
    tenantName: 'TechCorp Solutions',
    status: 'active',
    lastLogin: '2024-06-29T07:45:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    permissions: ['hr', 'payroll', 'performance'],
  },
  {
    id: '5',
    email: 'michael@healthfirst.com',
    name: 'Dr. Michael Chen',
    role: 'admin',
    tenantId: '2',
    tenantName: 'HealthFirst Medical',
    status: 'active',
    lastLogin: '2024-06-28T16:30:00Z',
    createdAt: '2024-03-22T09:00:00Z',
    permissions: ['hr', 'payroll'],
  },
  {
    id: '6',
    email: 'emily@retailmax.com',
    name: 'Emily Rodriguez',
    role: 'admin',
    tenantId: '3',
    tenantName: 'RetailMax Inc',
    status: 'active',
    lastLogin: '2024-06-27T11:00:00Z',
    createdAt: '2024-05-10T08:00:00Z',
    permissions: ['hr', 'payroll'],
  },
  {
    id: '7',
    email: 'james@edulearn.com',
    name: 'Prof. James Wilson',
    role: 'admin',
    tenantId: '4',
    tenantName: 'EduLearn Academy',
    status: 'pending',
    createdAt: '2024-06-25T12:00:00Z',
    permissions: [],
  },
];

// Mock modules
export const mockModules: Module[] = [
  {
    id: 'hr',
    name: 'HR Management',
    slug: 'hr',
    description: 'Complete HR management including employee records, onboarding, and offboarding',
    category: 'hr',
    status: 'active',
    price: 0,
    icon: 'Users',
    required: true,
    tier: 'starter',
  },
  {
    id: 'payroll',
    name: 'Payroll',
    slug: 'payroll',
    description: 'Automated payroll processing, tax calculations, and compliance',
    category: 'finance',
    status: 'active',
    price: 0,
    icon: 'DollarSign',
    required: true,
    tier: 'starter',
  },
  {
    id: 'performance',
    name: 'Performance Management',
    slug: 'performance',
    description: 'OKRs, performance reviews, and 360 feedback',
    category: 'hr',
    status: 'active',
    price: 299,
    icon: 'TrendingUp',
    required: false,
    tier: 'professional',
  },
  {
    id: 'analytics',
    name: 'Advanced Analytics',
    slug: 'analytics',
    description: 'Real-time dashboards, reports, and workforce insights',
    category: 'analytics',
    status: 'active',
    price: 499,
    icon: 'BarChart3',
    required: false,
    tier: 'professional',
  },
  {
    id: 'document',
    name: 'Document Management',
    slug: 'document',
    description: 'Secure document storage, e-signatures, and version control',
    category: 'core',
    status: 'active',
    price: 199,
    icon: 'FileText',
    required: false,
    tier: 'starter',
  },
  {
    id: 'project',
    name: 'Project Management',
    slug: 'project',
    description: 'Project planning, task management, and team collaboration',
    category: 'core',
    status: 'active',
    price: 399,
    icon: 'Kanban',
    required: false,
    tier: 'professional',
  },
  {
    id: 'calendar',
    name: 'Smart Calendar',
    slug: 'calendar',
    description: 'AI-powered scheduling, meeting management, and availability',
    category: 'core',
    status: 'active',
    price: 149,
    icon: 'Calendar',
    required: false,
    tier: 'starter',
  },
  {
    id: 'video',
    name: 'Video Conferencing',
    slug: 'video',
    description: 'HD video meetings, screen sharing, and recording',
    category: 'core',
    status: 'active',
    price: 249,
    icon: 'Video',
    required: false,
    tier: 'professional',
  },
  {
    id: 'learning',
    name: 'Learning Management',
    slug: 'learning',
    description: 'Course creation, training tracks, and compliance training',
    category: 'hr',
    status: 'active',
    price: 349,
    icon: 'GraduationCap',
    required: false,
    tier: 'professional',
  },
  {
    id: 'compensation',
    name: 'Compensation Planning',
    slug: 'compensation',
    description: 'Salary bands, variable pay, and equity management',
    category: 'finance',
    status: 'beta',
    price: 599,
    icon: 'Award',
    required: false,
    tier: 'enterprise',
  },
  {
    id: 'crm',
    name: 'CRM Integration',
    slug: 'crm',
    description: 'Salesforce, HubSpot, and custom CRM integrations',
    category: 'integrations',
    status: 'active',
    price: 299,
    icon: 'Link',
    required: false,
    tier: 'professional',
  },
  {
    id: 'ai',
    name: 'AI Assistant',
    slug: 'ai',
    description: 'HR copilot, writing assistant, and smart automation',
    category: 'core',
    status: 'active',
    price: 799,
    icon: 'Bot',
    required: false,
    tier: 'enterprise',
  },
];

// Mock tenant modules
export const mockTenantModules: TenantModule[] = [
  { tenantId: '1', tenantName: 'TechCorp Solutions', moduleId: 'hr', moduleName: 'HR Management', status: 'active', assignedAt: '2024-01-15T10:00:00Z', usage: 450, limit: 500 },
  { tenantId: '1', tenantName: 'TechCorp Solutions', moduleId: 'payroll', moduleName: 'Payroll', status: 'active', assignedAt: '2024-01-15T10:00:00Z', usage: 450, limit: 500 },
  { tenantId: '1', tenantName: 'TechCorp Solutions', moduleId: 'performance', moduleName: 'Performance Management', status: 'active', assignedAt: '2024-02-01T10:00:00Z', usage: 320, limit: 500 },
  { tenantId: '1', tenantName: 'TechCorp Solutions', moduleId: 'analytics', moduleName: 'Advanced Analytics', status: 'active', assignedAt: '2024-03-01T10:00:00Z', usage: 280, limit: 500 },
  { tenantId: '1', tenantName: 'TechCorp Solutions', moduleId: 'document', moduleName: 'Document Management', status: 'active', assignedAt: '2024-01-15T10:00:00Z', usage: 1250, limit: 5000 },
  { tenantId: '2', tenantName: 'HealthFirst Medical', moduleId: 'hr', moduleName: 'HR Management', status: 'active', assignedAt: '2024-03-22T09:00:00Z', usage: 125, limit: 150 },
  { tenantId: '2', tenantName: 'HealthFirst Medical', moduleId: 'payroll', moduleName: 'Payroll', status: 'active', assignedAt: '2024-03-22T09:00:00Z', usage: 125, limit: 150 },
  { tenantId: '2', tenantName: 'HealthFirst Medical', moduleId: 'performance', moduleName: 'Performance Management', status: 'trial', assignedAt: '2024-06-15T09:00:00Z', expiresAt: '2024-07-15T09:00:00Z', usage: 45, limit: 150 },
];

// Mock billing records
export const mockBillingRecords: BillingRecord[] = [
  {
    id: '1',
    tenantId: '1',
    tenantName: 'TechCorp Solutions',
    amount: 9999,
    currency: 'USD',
    status: 'paid',
    type: 'subscription',
    description: 'Enterprise Plan - Monthly',
    invoiceUrl: '#',
    dueDate: '2024-06-01T00:00:00Z',
    paidAt: '2024-06-01T10:30:00Z',
    createdAt: '2024-05-25T00:00:00Z',
  },
  {
    id: '2',
    tenantId: '2',
    tenantName: 'HealthFirst Medical',
    amount: 1999,
    currency: 'USD',
    status: 'paid',
    type: 'subscription',
    description: 'Professional Plan - Monthly',
    invoiceUrl: '#',
    dueDate: '2024-06-22T00:00:00Z',
    paidAt: '2024-06-22T08:15:00Z',
    createdAt: '2024-05-25T00:00:00Z',
  },
  {
    id: '3',
    tenantId: '3',
    tenantName: 'RetailMax Inc',
    amount: 499,
    currency: 'USD',
    status: 'pending',
    type: 'subscription',
    description: 'Starter Plan - Monthly',
    dueDate: '2024-07-10T00:00:00Z',
    createdAt: '2024-06-10T00:00:00Z',
  },
  {
    id: '4',
    tenantId: '5',
    tenantName: 'GreenEnergy Corp',
    amount: 9999,
    currency: 'USD',
    status: 'paid',
    type: 'subscription',
    description: 'Enterprise Plan - Monthly',
    invoiceUrl: '#',
    dueDate: '2024-06-05T00:00:00Z',
    paidAt: '2024-06-05T14:20:00Z',
    createdAt: '2024-05-28T00:00:00Z',
  },
  {
    id: '5',
    tenantId: '5',
    tenantName: 'GreenEnergy Corp',
    amount: 798,
    currency: 'USD',
    status: 'paid',
    type: 'addon',
    description: 'Additional 200 users',
    invoiceUrl: '#',
    dueDate: '2024-06-05T00:00:00Z',
    paidAt: '2024-06-05T14:25:00Z',
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: '6',
    tenantId: '6',
    tenantName: 'FinanceHub Partners',
    amount: 9999,
    currency: 'USD',
    status: 'overdue',
    type: 'subscription',
    description: 'Enterprise Plan - Monthly',
    dueDate: '2024-05-15T00:00:00Z',
    createdAt: '2024-05-01T00:00:00Z',
  },
  {
    id: '7',
    tenantId: '7',
    tenantName: 'MediaWorks Studio',
    amount: 1999,
    currency: 'USD',
    status: 'paid',
    type: 'subscription',
    description: 'Professional Plan - Monthly',
    invoiceUrl: '#',
    dueDate: '2024-06-28T00:00:00Z',
    paidAt: '2024-06-28T11:00:00Z',
    createdAt: '2024-05-28T00:00:00Z',
  },
  {
    id: '8',
    tenantId: '8',
    tenantName: 'LogiTrans Logistics',
    amount: 499,
    currency: 'USD',
    status: 'pending',
    type: 'subscription',
    description: 'Starter Plan - Monthly',
    dueDate: '2024-07-12T00:00:00Z',
    createdAt: '2024-06-12T00:00:00Z',
  },
];

// Mock API keys
export const mockApiKeys: ApiKey[] = [
  {
    id: '1',
    name: 'Production API Key',
    key: 'cpk_live_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6',
    tenantId: '1',
    tenantName: 'TechCorp Solutions',
    permissions: ['read', 'write', 'webhooks'],
    status: 'active',
    createdAt: '2024-01-15T10:00:00Z',
    expiresAt: '2025-01-15T10:00:00Z',
    lastUsed: '2024-06-29T08:45:00Z',
    usageCount: 125000,
  },
  {
    id: '2',
    name: 'Development API Key',
    key: 'cpk_test_x1y2z3a4b5c6d7e8f9g0h1i2j3k4l5m6',
    tenantId: '1',
    tenantName: 'TechCorp Solutions',
    permissions: ['read', 'write'],
    status: 'active',
    createdAt: '2024-02-01T10:00:00Z',
    lastUsed: '2024-06-28T16:30:00Z',
    usageCount: 45000,
  },
  {
    id: '3',
    name: 'HealthFirst Integration',
    key: 'cpk_live_p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2',
    tenantId: '2',
    tenantName: 'HealthFirst Medical',
    permissions: ['read'],
    status: 'active',
    createdAt: '2024-03-22T09:00:00Z',
    expiresAt: '2025-03-22T09:00:00Z',
    lastUsed: '2024-06-29T07:15:00Z',
    usageCount: 45000,
  },
  {
    id: '4',
    name: 'Platform Internal Key',
    key: 'cpk_int_d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8',
    permissions: ['all'],
    status: 'active',
    createdAt: '2023-01-01T00:00:00Z',
    lastUsed: '2024-06-29T09:00:00Z',
    usageCount: 2500000,
  },
  {
    id: '5',
    name: 'GreenEnergy Webhooks',
    key: 'cpk_live_t9u0v1w2x3y4z5a6b7c8d9e0f1g2h3i4',
    tenantId: '5',
    tenantName: 'GreenEnergy Corp',
    permissions: ['webhooks'],
    status: 'active',
    createdAt: '2023-11-05T10:00:00Z',
    expiresAt: '2024-11-05T10:00:00Z',
    lastUsed: '2024-06-29T06:00:00Z',
    usageCount: 210000,
  },
  {
    id: '6',
    name: 'Deprecated Integration',
    key: 'cpk_old_j5k6l7m8n9o0p1q2r3s4t5u6v7w8x9y0',
    tenantId: '3',
    tenantName: 'RetailMax Inc',
    permissions: ['read'],
    status: 'expired',
    createdAt: '2024-05-10T08:00:00Z',
    expiresAt: '2024-06-10T08:00:00Z',
    lastUsed: '2024-06-08T12:00:00Z',
    usageCount: 12000,
  },
];

// Mock platform analytics
export const mockAnalytics: PlatformAnalytics = {
  totalUsers: 1843,
  totalTenants: 8,
  totalRevenue: 52491,
  mrr: 25993,
  arr: 311916,
  apiCalls: 541500,
  storageUsed: 100700000000,
  growthRate: 12.5,
  churnRate: 2.3,
  activeUsers: 1650,
  newTenantsThisMonth: 2,
  newUsersThisMonth: 145,
};

// Mock usage trends (last 7 days)
export const mockUsageTrends: UsageTrend[] = [
  { date: '2024-06-23', users: 1780, apiCalls: 75000, revenue: 25000 },
  { date: '2024-06-24', users: 1792, apiCalls: 78000, revenue: 25200 },
  { date: '2024-06-25', users: 1805, apiCalls: 82000, revenue: 25500 },
  { date: '2024-06-26', users: 1818, apiCalls: 85000, revenue: 25800 },
  { date: '2024-06-27', users: 1825, apiCalls: 79000, revenue: 25900 },
  { date: '2024-06-28', users: 1838, apiCalls: 86000, revenue: 26100 },
  { date: '2024-06-29', users: 1843, apiCalls: 89500, revenue: 26491 },
];

// Computed stats
export const mockTenantStats: TenantStats = {
  total: 8,
  active: 5,
  inactive: 1,
  pending: 1,
  suspended: 1,
  newThisMonth: 2,
  churnedThisMonth: 0,
};

export const mockUserStats: UserStats = {
  total: 7,
  active: 6,
  inactive: 0,
  pending: 1,
  newThisWeek: 1,
  byRole: {
    super_admin: 1,
    admin: 4,
    support: 1,
  },
};

export const mockBillingStats: BillingStats = {
  totalRevenue: 52491,
  mrr: 25993,
  arr: 311916,
  pendingPayments: 4998,
  overduePayments: 9999,
  averageRevenuePerTenant: 6561,
  revenueByPlan: {
    starter: 998,
    professional: 7996,
    enterprise: 43497,
  },
  revenueByMonth: [
    { month: 'Jan', revenue: 35000 },
    { month: 'Feb', revenue: 38500 },
    { month: 'Mar', revenue: 42000 },
    { month: 'Apr', revenue: 44500 },
    { month: 'May', revenue: 48000 },
    { month: 'Jun', revenue: 52491 },
  ],
};

export const mockDashboardStats: DashboardStats = {
  tenants: mockTenantStats,
  users: mockUserStats,
  billing: mockBillingStats,
  analytics: mockAnalytics,
};
