import PDFDocument from 'pdfkit';
import { Parser } from 'json2csv';
import { RevenueData, OrderData, CustomerMetrics, MerchantPerformance, DashboardSummary } from '../types';

/**
 * Export data to CSV format
 */
export function exportToCSV(data: unknown, type: string): string {
  try {
    let flattenedData: Record<string, unknown>[] = [];

    if (Array.isArray(data)) {
      // Handle array data (revenue, orders, merchants)
      flattenedData = data.map(item => flattenObject(item as Record<string, unknown>));
    } else if (typeof data === 'object' && data !== null) {
      // Handle object data (customers, dashboard summary)
      flattenedData = [flattenObject(data as Record<string, unknown>)];
    }

    const fields = getFieldsForType(type);
    const parser = new Parser({ fields });
    return parser.parse(flattenedData);
  } catch (error) {
    logger.error('Error exporting to CSV:', error);
    throw new Error('Failed to generate CSV');
  }
}

/**
 * Export data to PDF format
 */
export async function exportToPDF(data: unknown, type: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).text('Analytics Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Report Type: ${type.toUpperCase()}`, { align: 'center' });
      doc.text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
      doc.moveDown(2);

      // Content based on type
      if (type === 'revenue' && Array.isArray(data)) {
        renderRevenuePDF(doc, data as RevenueData[]);
      } else if (type === 'orders' && Array.isArray(data)) {
        renderOrdersPDF(doc, data as OrderData[]);
      } else if (type === 'customers' && typeof data === 'object') {
        renderCustomersPDF(doc, data as CustomerMetrics);
      } else if (type === 'merchants' && Array.isArray(data)) {
        renderMerchantsPDF(doc, data as MerchantPerformance[]);
      } else if (type === 'full' && typeof data === 'object') {
        renderFullDashboardPDF(doc, data as DashboardSummary);
      } else {
        doc.fontSize(14).text('Data export');
        doc.moveDown();
        doc.fontSize(10).text(JSON.stringify(data, null, 2));
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).text(
        'Generated by ReZ Analytics Service',
        50,
        doc.page.height - 50,
        { align: 'center' }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// Helper functions

function flattenObject(obj: Record<string, unknown>, prefix: string = ''): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}.${key}` : key;

    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(result, flattenObject(value as Record<string, unknown>, newKey));
    } else if (Array.isArray(value)) {
      result[newKey] = JSON.stringify(value);
    } else {
      result[newKey] = value;
    }
  }

  return result;
}

function getFieldsForType(type: string): string[] {
  const fieldMap: Record<string, string[]> = {
    revenue: ['date', 'revenue', 'orders', 'refunds'],
    orders: ['orderId', 'customerId', 'merchantId', 'amount', 'status', 'createdAt', 'completedAt'],
    customers: ['totalCustomers', 'newCustomers', 'returningCustomers', 'churnRate', 'lifetimeValue', 'averagePurchaseFrequency'],
    merchants: ['merchantId', 'merchantName', 'totalSales', 'orderCount', 'averageRating', 'responseTime', 'fulfillmentRate'],
    full: ['kpis.totalRevenue', 'kpis.totalOrders', 'kpis.activeCustomers', 'kpis.averageOrderValue', 'lastUpdated'],
  };

  return fieldMap[type] || [];
}

function renderRevenuePDF(doc: PDFKit.PDFDocument, data: RevenueData[]): void {
  doc.fontSize(16).text('Revenue Report');
  doc.moveDown();

  // Summary
  const totalRevenue = data.reduce((sum, r) => sum + r.revenue, 0);
  const totalOrders = data.reduce((sum, r) => sum + r.orders, 0);
  const totalRefunds = data.reduce((sum, r) => sum + r.refunds, 0);

  doc.fontSize(12).text('Summary');
  doc.fontSize(10);
  doc.text(`Total Revenue: $${totalRevenue.toFixed(2)}`);
  doc.text(`Total Orders: ${totalOrders}`);
  doc.text(`Total Refunds: $${totalRefunds.toFixed(2)}`);
  doc.text(`Net Revenue: $${(totalRevenue - totalRefunds).toFixed(2)}`);
  doc.moveDown();

  // Table header
  doc.fontSize(10).font('Helvetica-Bold');
  doc.text('Date', 50, doc.y, { width: 100 });
  doc.text('Revenue', 150, doc.y - 10, { width: 100 });
  doc.text('Orders', 250, doc.y - 20, { width: 100 });
  doc.text('Refunds', 350, doc.y - 30, { width: 100 });
  doc.font('Helvetica');

  // Table rows
  data.slice(0, 50).forEach(row => {
    doc.text(row.date, 50, doc.y, { width: 100 });
    doc.text(`$${row.revenue.toFixed(2)}`, 150, doc.y - 10, { width: 100 });
    doc.text(row.orders.toString(), 250, doc.y - 20, { width: 100 });
    doc.text(`$${row.refunds.toFixed(2)}`, 350, doc.y - 30, { width: 100 });
  });
}

function renderOrdersPDF(doc: PDFKit.PDFDocument, data: OrderData[]): void {
  doc.fontSize(16).text('Orders Report');
  doc.moveDown();

  // Summary
  const statusCounts = { pending: 0, completed: 0, cancelled: 0, refunded: 0 };
  data.forEach(o => {
    if (o.status in statusCounts) {
      statusCounts[o.status as keyof typeof statusCounts]++;
    }
  });

  doc.fontSize(12).text('Summary');
  doc.fontSize(10);
  doc.text(`Total Orders: ${data.length}`);
  doc.text(`Completed: ${statusCounts.completed}`);
  doc.text(`Pending: ${statusCounts.pending}`);
  doc.text(`Cancelled: ${statusCounts.cancelled}`);
  doc.text(`Refunded: ${statusCounts.refunded}`);
  doc.moveDown();

  // Table header
  doc.fontSize(10).font('Helvetica-Bold');
  doc.text('Order ID', 50, doc.y);
  doc.text('Customer', 180, doc.y);
  doc.text('Amount', 310, doc.y);
  doc.text('Status', 400, doc.y);
  doc.font('Helvetica');

  // Table rows
  data.slice(0, 30).forEach(order => {
    const truncatedId = order.orderId.substring(0, 8);
    doc.text(truncatedId, 50, doc.y);
    doc.text(order.customerId, 180, doc.y);
    doc.text(`$${order.amount.toFixed(2)}`, 310, doc.y);
    doc.text(order.status, 400, doc.y);
  });
}

function renderCustomersPDF(doc: PDFKit.PDFDocument, data: CustomerMetrics): void {
  doc.fontSize(16).text('Customer Metrics Report');
  doc.moveDown();

  doc.fontSize(12).text('Customer Statistics');
  doc.fontSize(10).moveDown();

  const metrics = [
    ['Total Customers', data.totalCustomers.toString()],
    ['New Customers', data.newCustomers.toString()],
    ['Returning Customers', data.returningCustomers.toString()],
    ['Churn Rate', `${data.churnRate}%`],
    ['Lifetime Value', `$${data.lifetimeValue.toFixed(2)}`],
    ['Avg Purchase Frequency', data.averagePurchaseFrequency.toFixed(2)],
  ];

  metrics.forEach(([label, value]) => {
    doc.text(`${label}: ${value}`);
  });
}

function renderMerchantsPDF(doc: PDFKit.PDFDocument, data: MerchantPerformance[]): void {
  doc.fontSize(16).text('Merchant Performance Report');
  doc.moveDown();

  // Table header
  doc.fontSize(10).font('Helvetica-Bold');
  doc.text('Merchant', 50, doc.y);
  doc.text('Sales', 200, doc.y);
  doc.text('Orders', 300, doc.y);
  doc.text('Rating', 380, doc.y);
  doc.font('Helvetica');

  // Table rows
  data.slice(0, 20).forEach(merchant => {
    doc.text(merchant.merchantName.substring(0, 25), 50, doc.y);
    doc.text(`$${merchant.totalSales.toFixed(2)}`, 200, doc.y);
    doc.text(merchant.orderCount.toString(), 300, doc.y);
    doc.text(merchant.averageRating.toString(), 380, doc.y);
  });
}

function renderFullDashboardPDF(doc: PDFKit.PDFDocument, data: DashboardSummary): void {
  doc.fontSize(16).text('Dashboard Summary Report');
  doc.moveDown();

  // KPIs
  doc.fontSize(14).text('Key Performance Indicators');
  doc.fontSize(10).moveDown();

  const kpis = [
    ['Total Revenue', `$${data.kpis.totalRevenue.toFixed(2)}`, `(${data.kpis.revenueGrowth}%)`],
    ['Total Orders', data.kpis.totalOrders.toString(), `(${data.kpis.ordersGrowth}%)`],
    ['Average Order Value', `$${data.kpis.averageOrderValue.toFixed(2)}`, `(${data.kpis.aovGrowth}%)`],
    ['Active Customers', data.kpis.activeCustomers.toString(), `(${data.kpis.customerGrowth}%)`],
    ['Conversion Rate', `${data.kpis.conversionRate}%`, `(${data.kpis.conversionGrowth}%)`],
  ];

  kpis.forEach(([label, value, growth]) => {
    doc.text(`${label}: ${value} ${growth}`);
  });

  doc.moveDown();

  // Top Products
  doc.fontSize(14).text('Top Products');
  doc.fontSize(10).moveDown();

  doc.font('Helvetica-Bold');
  doc.text('Product', 50, doc.y);
  doc.text('Units Sold', 200, doc.y);
  doc.text('Revenue', 300, doc.y);
  doc.font('Helvetica');

  data.topProducts.slice(0, 5).forEach(product => {
    doc.text(product.productName.substring(0, 25), 50, doc.y);
    doc.text(product.unitsSold.toString(), 200, doc.y);
    doc.text(`$${product.revenue.toFixed(2)}`, 300, doc.y);
  });

  doc.moveDown();

  // Top Merchants
  doc.fontSize(14).text('Top Merchants');
  doc.fontSize(10).moveDown();

  doc.font('Helvetica-Bold');
  doc.text('Merchant', 50, doc.y);
  doc.text('Sales', 200, doc.y);
  doc.text('Orders', 300, doc.y);
  doc.font('Helvetica');

  data.topMerchants.slice(0, 5).forEach(merchant => {
    doc.text(merchant.merchantName.substring(0, 25), 50, doc.y);
    doc.text(`$${merchant.totalSales.toFixed(2)}`, 200, doc.y);
    doc.text(merchant.orderCount.toString(), 300, doc.y);
  });

  doc.moveDown();
  doc.text(`Report generated at: ${data.lastUpdated}`);
}

// Type declaration for PDFKit module
declare namespace PDFKit {
  interface PDFDocument {
    font(name: string): this;
    fontSize(size: number): this;
    text(text: string, x?: number, y?: number, options?: { align?: string; width?: number }): this;
    moveDown(lines?: number): this;
    moveUp(lines?: number): this;
    moveTo(x: number, y: number): this;
    lineTo(x: number, y: number): this;
    stroke(): this;
    rect(x: number, y: number, width: number, height: number): this;
    fill(options?: { stroke?: boolean }): this;
    page: { height: number };
    y: number;
    addPage(): this;
    end(): void;
    on(event: string, callback: (data: Buffer) => void): this;
  }
}
