apiVersion: v1
kind: Service
metadata:
  name: atlas-email-service
  namespace: rez-merchant
  labels:
    app: atlas-email-service
    managed-by: rez-merchant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5161
      targetPort: http
      protocol: TCP
  selector:
    app: atlas-email-service