apiVersion: v1
kind: Service
metadata:
  name: neighborai
  namespace: hojai
  labels:
    app: neighborai
    company: hojai-ai
    industry: society
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4806
      protocol: TCP
      name: http
  selector:
    app: neighborai