# Kubernetes Service for REZ-atlas-territory
apiVersion: v1
kind: Service
metadata:
  name: REZ-atlas-territory
  namespace: rez-merchant
  labels:
    app: REZ-atlas-territory
    managed-by: rez-merchant
  annotations:
    description: "REZ-atlas-territory service"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5170
      targetPort: http
      protocol: TCP
  selector:
    app: REZ-atlas-territory
