// Mock data for development and demonstration
import type {
  Employee,
  Department,
  AuditLog,
  SystemHealth,
  Notification,
  AnalyticsOverview,
  ModuleMetrics,
  QuickAction,
} from '@/types';

// Departments
export const departments: Department[] = [
  { id: 'dept-1', name: 'Engineering', code: 'ENG', employeeCount: 45 },
  { id: 'dept-2', name: 'Product', code: 'PROD', employeeCount: 12 },
  { id: 'dept-3', name: 'Design', code: 'DES', employeeCount: 8 },
  { id: 'dept-4', name: 'Marketing', code: 'MKT', employeeCount: 15 },
  { id: 'dept-5', name: 'Sales', code: 'SLS', employeeCount: 22 },
  { id: 'dept-6', name: 'Human Resources', code: 'HR', employeeCount: 6 },
  { id: 'dept-7', name: 'Finance', code: 'FIN', employeeCount: 8 },
  { id: 'dept-8', name: 'Operations', code: 'OPS', employeeCount: 18 },
];

// Mock Employees
export const employees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'CP001',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@corpperks.com',
    phone: '+91 98765 43210',
    department: departments[0],
    designation: 'Senior Software Engineer',
    joinDate: '2022-03-15',
    status: 'active',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 1800000, currency: 'INR', bonus: 180000 },
    skills: ['React', 'Node.js', 'TypeScript', 'AWS'],
    certifications: [
      {
        id: 'cert-1',
        name: 'AWS Solutions Architect',
        issuedBy: 'Amazon',
        issuedDate: '2024-01-15',
        status: 'valid',
      },
    ],
  },
  {
    id: 'emp-2',
    employeeId: 'CP002',
    firstName: 'Rahul',
    lastName: 'Verma',
    email: 'rahul.verma@corpperks.com',
    phone: '+91 98765 43211',
    department: departments[0],
    designation: 'Engineering Manager',
    joinDate: '2020-08-01',
    status: 'active',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 2500000, currency: 'INR', bonus: 375000 },
    skills: ['Leadership', 'System Design', 'Python', 'Kubernetes'],
    certifications: [],
  },
  {
    id: 'emp-3',
    employeeId: 'CP003',
    firstName: 'Ananya',
    lastName: 'Reddy',
    email: 'ananya.reddy@corpperks.com',
    phone: '+91 98765 43212',
    department: departments[1],
    designation: 'Product Manager',
    joinDate: '2021-06-10',
    status: 'active',
    location: 'Mumbai',
    employmentType: 'full_time',
    salary: { base: 2200000, currency: 'INR', bonus: 264000 },
    skills: ['Product Strategy', 'Agile', 'Data Analysis', 'Figma'],
    certifications: [],
  },
  {
    id: 'emp-4',
    employeeId: 'CP004',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@corpperks.com',
    phone: '+91 98765 43213',
    department: departments[2],
    designation: 'UI/UX Designer',
    joinDate: '2023-01-20',
    status: 'active',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 1200000, currency: 'INR' },
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    certifications: [],
  },
  {
    id: 'emp-5',
    employeeId: 'CP005',
    firstName: 'Meera',
    lastName: 'Patel',
    email: 'meera.patel@corpperks.com',
    phone: '+91 98765 43214',
    department: departments[3],
    designation: 'Marketing Lead',
    joinDate: '2021-09-05',
    status: 'active',
    location: 'Delhi',
    employmentType: 'full_time',
    salary: { base: 1600000, currency: 'INR', bonus: 160000 },
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics'],
    certifications: [],
  },
  {
    id: 'emp-6',
    employeeId: 'CP006',
    firstName: 'Arjun',
    lastName: 'Nair',
    email: 'arjun.nair@corpperks.com',
    phone: '+91 98765 43215',
    department: departments[4],
    designation: 'Sales Manager',
    joinDate: '2022-04-18',
    status: 'active',
    location: 'Mumbai',
    employmentType: 'full_time',
    salary: { base: 1400000, currency: 'INR', bonus: 280000 },
    skills: ['B2B Sales', 'Negotiation', 'CRM', 'Account Management'],
    certifications: [],
  },
  {
    id: 'emp-7',
    employeeId: 'CP007',
    firstName: 'Kavya',
    lastName: 'Iyer',
    email: 'kavya.iyer@corpperks.com',
    phone: '+91 98765 43216',
    department: departments[5],
    designation: 'HR Manager',
    joinDate: '2020-11-30',
    status: 'active',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 1500000, currency: 'INR', bonus: 150000 },
    skills: ['Talent Acquisition', 'Employee Relations', 'HRIS', 'Compliance'],
    certifications: [],
  },
  {
    id: 'emp-8',
    employeeId: 'CP008',
    firstName: 'Sanjay',
    lastName: 'Gupta',
    email: 'sanjay.gupta@corpperks.com',
    phone: '+91 98765 43217',
    department: departments[6],
    designation: 'Finance Manager',
    joinDate: '2021-02-14',
    status: 'active',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 1800000, currency: 'INR', bonus: 216000 },
    skills: ['Financial Planning', 'Budgeting', 'Tax', 'Audit'],
    certifications: [],
  },
  {
    id: 'emp-9',
    employeeId: 'CP009',
    firstName: 'Neha',
    lastName: 'Kapoor',
    email: 'neha.kapoor@corpperks.com',
    phone: '+91 98765 43218',
    department: departments[7],
    designation: 'Operations Lead',
    joinDate: '2022-07-25',
    status: 'on_leave',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 1300000, currency: 'INR' },
    skills: ['Process Optimization', 'Supply Chain', 'Project Management'],
    certifications: [],
  },
  {
    id: 'emp-10',
    employeeId: 'CP010',
    firstName: 'Aditya',
    lastName: 'Menon',
    email: 'aditya.menon@corpperks.com',
    phone: '+91 98765 43219',
    department: departments[0],
    designation: 'Software Engineer',
    joinDate: '2024-02-01',
    status: 'probation',
    location: 'Bangalore',
    employmentType: 'full_time',
    salary: { base: 800000, currency: 'INR' },
    skills: ['JavaScript', 'Python', 'SQL'],
    certifications: [],
  },
];

// Analytics Overview
export const analyticsOverview: AnalyticsOverview = {
  totalEmployees: 134,
  activeEmployees: 128,
  newHires: 8,
  departures: 3,
  averageTenure: 2.4,
  retentionRate: 94.2,
  employeeGrowth: 6.2,
};

// Module Metrics
export const moduleMetrics: ModuleMetrics = {
  attendance: {
    present: 118,
    absent: 4,
    late: 6,
    remote: 42,
    onTime: 112,
    rate: 94.2,
  },
  leave: {
    pending: 12,
    approved: 45,
    rejected: 8,
    total: 65,
    typesBreakdown: {
      sick: 18,
      casual: 22,
      earned: 15,
      parental: 6,
      unpaid: 4,
    },
  },
  payroll: {
    totalAmount: 18500000,
    processed: 126,
    pending: 8,
    failed: 0,
    averageSalary: 138000,
  },
  performance: {
    submitted: 98,
    pending: 36,
    averageRating: 3.8,
    goalsCompleted: 245,
    goalsAtRisk: 28,
  },
  training: {
    enrolled: 312,
    completed: 198,
    inProgress: 114,
    completionRate: 63.5,
  },
};

// System Health
export const systemHealth: SystemHealth = {
  status: 'healthy',
  uptime: 99.8,
  lastChecked: new Date().toISOString(),
  services: [
    { name: 'API Gateway', status: 'up', latency: 45, lastPing: new Date().toISOString() },
    { name: 'Auth Service', status: 'up', latency: 32, lastPing: new Date().toISOString() },
    { name: 'Employee Service', status: 'up', latency: 28, lastPing: new Date().toISOString() },
    { name: 'Payroll Service', status: 'up', latency: 56, lastPing: new Date().toISOString() },
    { name: 'Attendance Service', status: 'up', latency: 38, lastPing: new Date().toISOString() },
    { name: 'Leave Service', status: 'up', latency: 42, lastPing: new Date().toISOString() },
    { name: 'Database', status: 'up', latency: 12, lastPing: new Date().toISOString() },
    { name: 'Cache', status: 'up', latency: 2, lastPing: new Date().toISOString() },
  ],
};

// Notifications
export const notifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'Leave Request',
    message: 'Neha Kapoor has requested 5 days of sick leave',
    type: 'warning',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    read: false,
    actionUrl: '/employees',
  },
  {
    id: 'notif-2',
    title: 'Payroll Processed',
    message: 'May 2026 payroll has been successfully processed',
    type: 'success',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    read: true,
  },
  {
    id: 'notif-3',
    title: 'New Hire',
    message: 'Aditya Menon completed onboarding successfully',
    type: 'info',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: true,
    actionUrl: '/employees',
  },
  {
    id: 'notif-4',
    title: 'Performance Review Due',
    message: '36 employees have pending performance reviews',
    type: 'warning',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    actionUrl: '/analytics',
  },
  {
    id: 'notif-5',
    title: 'System Update',
    message: 'Scheduled maintenance on June 1st, 2:00 AM - 4:00 AM',
    type: 'info',
    timestamp: new Date(Date.now() - 43200000).toISOString(),
    read: false,
  },
];

// Quick Actions
export const quickActions: QuickAction[] = [
  {
    id: 'qa-1',
    title: 'Add Employee',
    description: 'Onboard a new team member',
    icon: 'UserPlus',
    href: '/employees?action=add',
  },
  {
    id: 'qa-2',
    title: 'Process Payroll',
    description: 'Run monthly payroll cycle',
    icon: 'Wallet',
    href: '/analytics?module=payroll',
  },
  {
    id: 'qa-3',
    title: 'Review Leaves',
    description: 'Approve or reject leave requests',
    icon: 'CalendarCheck',
    href: '/employees?tab=leaves',
    badge: '12',
    badgeColor: 'warning',
  },
  {
    id: 'qa-4',
    title: 'Generate Report',
    description: 'Create custom analytics report',
    icon: 'FileBarChart',
    href: '/analytics?action=report',
  },
  {
    id: 'qa-5',
    title: 'System Settings',
    description: 'Configure system preferences',
    icon: 'Settings',
    href: '/settings',
  },
  {
    id: 'qa-6',
    title: 'View Audit Logs',
    description: 'Monitor system activities',
    icon: 'Shield',
    href: '/audit',
  },
];

// Audit Logs
export const auditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    user: 'Kavya Iyer',
    userId: 'emp-7',
    action: 'create',
    module: 'employees',
    resource: 'Employee',
    resourceId: 'CP010',
    details: 'Created new employee record for Aditya Menon',
    status: 'success',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-2',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    user: 'Sanjay Gupta',
    userId: 'emp-8',
    action: 'approve',
    module: 'payroll',
    resource: 'Payroll',
    resourceId: 'MAY-2026',
    details: 'Approved payroll processing for May 2026',
    status: 'success',
    ipAddress: '192.168.1.105',
  },
  {
    id: 'audit-3',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    user: 'Kavya Iyer',
    userId: 'emp-7',
    action: 'update',
    module: 'settings',
    resource: 'Leave Policy',
    details: 'Updated casual leave entitlement from 12 to 15 days',
    status: 'success',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit-4',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    user: 'Rahul Verma',
    userId: 'emp-2',
    action: 'submit',
    module: 'performance',
    resource: 'Performance Review',
    resourceId: 'REV-2026-Q1-002',
    details: 'Submitted team performance reviews for Q1 2026',
    status: 'success',
    ipAddress: '192.168.1.102',
  },
  {
    id: 'audit-5',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    user: 'Priya Sharma',
    userId: 'emp-1',
    action: 'login',
    module: 'auth',
    resource: 'Session',
    details: 'Successful login from new device',
    status: 'success',
    ipAddress: '192.168.1.110',
    userAgent: 'Chrome/Windows',
  },
  {
    id: 'audit-6',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    user: 'Unknown',
    userId: 'unknown',
    action: 'login',
    module: 'auth',
    resource: 'Session',
    details: 'Failed login attempt - invalid credentials',
    status: 'failure',
    ipAddress: '203.0.113.50',
  },
  {
    id: 'audit-7',
    timestamp: new Date(Date.now() - 18000000).toISOString(),
    user: 'Ananya Reddy',
    userId: 'emp-3',
    action: 'export',
    module: 'employees',
    resource: 'Employee Data',
    details: 'Exported employee data report (134 records)',
    status: 'success',
    ipAddress: '192.168.1.103',
  },
  {
    id: 'audit-8',
    timestamp: new Date(Date.now() - 21600000).toISOString(),
    user: 'Meera Patel',
    userId: 'emp-5',
    action: 'update',
    module: 'employees',
    resource: 'Employee',
    resourceId: 'CP004',
    details: 'Updated Vikram Singh profile - new designation',
    status: 'success',
    ipAddress: '192.168.1.106',
  },
];

// Chart data
export const employeeGrowthData = [
  { month: 'Jan', count: 118 },
  { month: 'Feb', count: 120 },
  { month: 'Mar', count: 124 },
  { month: 'Apr', count: 126 },
  { month: 'May', count: 134 },
];

export const departmentDistribution = departments.map((d) => ({
  name: d.name,
  value: d.employeeCount,
}));

export const attendanceTrend = [
  { day: 'Mon', rate: 96 },
  { day: 'Tue', rate: 94 },
  { day: 'Wed', rate: 95 },
  { day: 'Thu', rate: 93 },
  { day: 'Fri', rate: 94 },
];

export const leaveDistribution = [
  { name: 'Sick', value: 18, color: '#ef4444' },
  { name: 'Casual', value: 22, color: '#f59e0b' },
  { name: 'Earned', value: 15, color: '#22c55e' },
  { name: 'Parental', value: 6, color: '#3b82f6' },
  { name: 'Unpaid', value: 4, color: '#6b7280' },
];
