apiVersion: v1
kind: Service
metadata:
  name: ad-bazaar-caption-generator
  labels:
    app: ad-bazaar-caption-generator
    tier: social-automation
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5091
    protocol: TCP
    name: http
  selector:
    app: ad-bazaar-caption-generator