import mongoose, { Document, Schema } from 'mongoose';

export type PrivacyStatus = 'public' | 'unlisted' | 'private';
export type VideoStatus = 'uploading' | 'processing' | 'published' | 'failed';

export interface IYouTubeVideo extends Document {
  id: string;
  youtubeVideoId: string;
  youtubeChannelId: string;
  title: string;
  description: string;
  tags: string[];
  categoryId: string;
  privacyStatus: PrivacyStatus;
  thumbnailUrl?: string;
  duration?: number;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  publishedAt?: Date;
  status: VideoStatus;
  errorMessage?: string;
  localFilePath?: string;
  youtubeResponse?: Record<string, unknown>;
  captions?: CaptionInfo[];
  endScreenData?: EndScreenData;
  createdAt: Date;
  updatedAt: Date;
}

export interface CaptionInfo {
  language: string;
  isAutoGenerated: boolean;
  captionId?: string;
}

export interface EndScreenData {
  elements: EndScreenElement[];
}

export interface EndScreenElement {
  type: 'video' | 'playlist' | 'channel' | 'subscribe';
  videoId?: string;
  playlistId?: string;
  channelId?: string;
  startSeconds: number;
  endSeconds: number;
  left: number;
  top: number;
  width: number;
  height: number;
}

const YouTubeVideoSchema = new Schema<IYouTubeVideo>(
  {
    id: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    youtubeVideoId: {
      type: String,
      index: true,
    },
    youtubeChannelId: {
      type: String,
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: '',
    },
    tags: {
      type: [String],
      default: [],
    },
    categoryId: {
      type: String,
      default: '22',
    },
    privacyStatus: {
      type: String,
      enum: ['public', 'unlisted', 'private'],
      default: 'private',
    },
    thumbnailUrl: {
      type: String,
    },
    duration: {
      type: Number,
    },
    viewCount: {
      type: Number,
      default: 0,
    },
    likeCount: {
      type: Number,
      default: 0,
    },
    commentCount: {
      type: Number,
      default: 0,
    },
    publishedAt: {
      type: Date,
    },
    status: {
      type: String,
      enum: ['uploading', 'processing', 'published', 'failed'],
      default: 'uploading',
    },
    errorMessage: {
      type: String,
    },
    localFilePath: {
      type: String,
    },
    youtubeResponse: {
      type: Schema.Types.Mixed,
    },
    captions: [{
      language: String,
      isAutoGenerated: Boolean,
      captionId: String,
    }],
    endScreenData: {
      type: Schema.Types.Mixed,
    },
  },
  {
    timestamps: true,
  }
);

YouTubeVideoSchema.index({ youtubeVideoId: 1 });
YouTubeVideoSchema.index({ youtubeChannelId: 1, status: 1 });
YouTubeVideoSchema.index({ publishedAt: -1 });
YouTubeVideoSchema.index({ status: 1 });

export const YouTubeVideo = mongoose.model<IYouTubeVideo>('YouTubeVideo', YouTubeVideoSchema);

export default YouTubeVideo;