/**
 * Civic Corps Service — Namma Bengaluru Karma Corps (NBKC)
 *
 * Core business logic for civic membership, green scoring, and mission management.
 */
import { logger } from '../config/logger.js';
import { NBKCMembership, GreenScoreProfile, CivicMission, CivicMissionEnrollment } from '../models/index.js';
import { KarmaProfile } from '../models/KarmaProfile.js';
import type { NBKCMembershipTier, GreenActionType, ICivicMission, IBadge } from '../models/index.js';
import { sendToUser } from './notificationService.js';
import { emitKarmaAwardedEvent } from '../utils/gamificationBridge.js';

// ─── Membership ─────────────────────────────────────────────────────────────────

export interface JoinMembershipParams {
  userId: string;
  ward: string;
  skills?: string[];
  hasVehicle?: boolean;
}

export interface MembershipResponse {
  membership: {
    memberNumber: string;
    tier: NBKCMembershipTier;
    ward: string;
    joinedAt: Date;
    perks: string[];
  };
  greenScore: number;
  greenBengaluruScore: number;
}

/**
 * Join NBKC as a citizen member.
 * Creates membership + green score profile.
 */
export async function joinCivicCorps(params: JoinMembershipParams): Promise<MembershipResponse> {
  const { userId, ward, skills = [], hasVehicle = false } = params;

  // Check existing membership
  const existing = await NBKCMembership.findOne({ userId: new (require('mongoose').Types.ObjectId)(userId) });
  if (existing) {
    throw new Error('Already a member of NBKC');
  }

  // Create membership
  const membership = await NBKCMembership.create({
    userId: new (require('mongoose').Types.ObjectId)(userId),
    memberNumber: '', // auto-generated by pre-save
    tier: 'citizen',
    ward,
    skills,
    hasVehicle,
    stickerIssued: false,
    isActive: true,
    totalCivicHours: 0,
    missionsCompleted: 0,
    civicReportsVerified: 0,
  });

  // Create green score profile
  const greenProfile = await GreenScoreProfile.create({
    userId: new (require('mongoose').Types.ObjectId)(userId),
  });

  logger.info('[NBKC] New member joined', {
    userId,
    memberNumber: membership.memberNumber,
    ward,
  });

  return {
    membership: {
      memberNumber: membership.memberNumber,
      tier: membership.tier,
      ward: membership.ward,
      joinedAt: membership.joinedAt,
      perks: membership.getPerks(),
    },
    greenScore: greenProfile.greenScore,
    greenBengaluruScore: greenProfile.greenBengaluruScore,
  };
}

/**
 * Get a user's NBKC membership status.
 */
export async function getCivicCorpsStatus(userId: string): Promise<{
  isMember: boolean;
  membership?: {
    memberNumber: string;
    tier: NBKCMembershipTier;
    ward: string;
    joinedAt: Date;
    totalCivicHours: number;
    missionsCompleted: number;
    stickerIssued: boolean;
    perks: string[];
    isEligibleForSticker: boolean;
  };
  greenScore: number;
  greenBengaluruScore: number;
}> {
  const { Types } = require('mongoose');
  const oid = new Types.ObjectId(userId);

  const [membership, greenProfile] = await Promise.all([
    NBKCMembership.findOne({ userId: oid }),
    GreenScoreProfile.findOne({ userId: oid }),
  ]);

  if (!membership) {
    return {
      isMember: false,
      greenScore: greenProfile?.greenScore ?? 0,
      greenBengaluruScore: greenProfile?.greenBengaluruScore ?? 0,
    };
  }

  return {
    isMember: true,
    membership: {
      memberNumber: membership.memberNumber,
      tier: membership.tier,
      ward: membership.ward,
      joinedAt: membership.joinedAt,
      totalCivicHours: membership.totalCivicHours,
      missionsCompleted: membership.missionsCompleted,
      stickerIssued: membership.stickerIssued,
      perks: membership.getPerks(),
      isEligibleForSticker: membership.isEligibleForSticker(),
    },
    greenScore: greenProfile?.greenScore ?? 0,
    greenBengaluruScore: greenProfile?.greenBengaluruScore ?? 0,
  };
}

// ─── Missions ─────────────────────────────────────────────────────────────────

export interface MissionListParams {
  ward?: string;
  category?: string;
  limit?: number;
  page?: number;
}

/**
 * List available civic missions.
 */
export async function listMissions(params: MissionListParams = {}): Promise<{
  missions: ICivicMission[];
  total: number;
  page: number;
}> {
  const { ward, category, limit = 20, page = 1 } = params;
  const skip = (page - 1) * limit;

  const filter: Record<string, unknown> = {
    status: 'active',
    scheduledAt: { $gte: new Date() },
  };
  if (ward) filter.ward = ward;
  if (category) filter.category = category;

  const [missions, total] = await Promise.all([
    CivicMission.find(filter).sort({ scheduledAt: 1 }).skip(skip).limit(limit),
    CivicMission.countDocuments(filter),
  ]);

  return { missions, total, page };
}

/**
 * Get mission details.
 */
export async function getMission(missionId: string) {
  return CivicMission.findById(missionId);
}

/**
 * Enroll in a civic mission.
 */
export async function enrollInMission(userId: string, missionId: string) {
  const { Types } = require('mongoose');
  const userOid = new Types.ObjectId(userId);
  const missionOid = new Types.ObjectId(missionId);

  const mission = await CivicMission.findById(missionOid);
  if (!mission) throw new Error('Mission not found');
  if (mission.status !== 'active') throw new Error('Mission is not active');
  if (mission.currentVolunteers >= mission.maxVolunteers) {
    throw new Error('Mission is full');
  }

  const existing = await CivicMissionEnrollment.findOne({ missionId: missionOid, userId: userOid });
  if (existing) throw new Error('Already enrolled in this mission');

  await Promise.all([
    CivicMissionEnrollment.create({ missionId: missionOid, userId: userOid }),
    CivicMission.findByIdAndUpdate(missionOid, { $inc: { currentVolunteers: 1 } }),
  ]);

  logger.info('[NBKC] User enrolled in mission', { userId, missionId });
  return { success: true };
}

/**
 * Check in to a mission.
 */
export async function checkInToMission(userId: string, missionId: string) {
  const { Types } = require('mongoose');
  const userOid = new Types.ObjectId(userId);
  const missionOid = new Types.ObjectId(missionId);

  const enrollment = await CivicMissionEnrollment.findOne({ missionId: missionOid, userId: userOid });
  if (!enrollment) throw new Error('Not enrolled in this mission');
  if (enrollment.checkedInAt) throw new Error('Already checked in');

  enrollment.checkedInAt = new Date();
  await enrollment.save();

  logger.info('[NBKC] User checked in', { userId, missionId });
  return { success: true, checkedInAt: enrollment.checkedInAt };
}

/**
 * Complete a civic mission and award karma + green score.
 */
export async function completeMission(
  userId: string,
  missionId: string,
  hoursVolunteered: number,
  verified = false
) {
  const { Types } = require('mongoose');
  const userOid = new Types.ObjectId(userId);
  const missionOid = new Types.ObjectId(missionId);

  const [enrollment, mission, karmaProfile] = await Promise.all([
    CivicMissionEnrollment.findOne({ missionId: missionOid, userId: userOid }),
    CivicMission.findById(missionOid),
    KarmaProfile.findOne({ userId: userOid }),
  ]);

  if (!enrollment) throw new Error('Not enrolled in this mission');
  if (!mission) throw new Error('Mission not found');

  // Calculate rewards
  const karmaEarned = Math.round(mission.karmaReward * (verified ? 1.0 : 0.8));
  const greenEarned = Math.round(mission.greenScoreReward * (verified ? 1.0 : 0.5));

  // Update enrollment
  enrollment.completedAt = new Date();
  enrollment.hoursVolunteered = hoursVolunteered;
  enrollment.karmaEarned = karmaEarned;
  enrollment.greenScoreEarned = greenEarned;
  enrollment.verified = verified;
  await enrollment.save();

  // Update membership stats
  await NBKCMembership.findOneAndUpdate(
    { userId: userOid },
    {
      $inc: { totalCivicHours: hoursVolunteered, missionsCompleted: 1 },
    }
  );

  // Update green score profile
  await addGreenAction(userId, {
    actionType: mapMissionToGreenAction(mission.category),
    karmaEarned: greenEarned,
    ward: mission.ward,
    verified,
  });

  // Award karma to karma profile
  if (karmaProfile && karmaEarned > 0) {
    karmaProfile.lifetimeKarma += karmaEarned;
    karmaProfile.activeKarma += karmaEarned;
    karmaProfile.eventsCompleted += 1;
    karmaProfile.totalHours += hoursVolunteered;
    karmaProfile.lastActivityAt = new Date();
    await karmaProfile.save();

    await emitKarmaAwardedEvent({
      userId,
      karmaAmount: karmaEarned,
      eventId: missionId,
      eventType: 'civic_mission',
      source: 'nbkc',
    });

    // Check for tier upgrade
    await checkAndUpgradeMembership(userId);
  }

  // Check for NBKC badges
  await checkNBKCBadges(userId, mission);

  logger.info('[NBKC] Mission completed', { userId, missionId, karmaEarned, greenEarned });

  return { karmaEarned, greenEarned, hoursVolunteered };
}

// ─── Green Score ─────────────────────────────────────────────────────────────

interface GreenActionParams {
  actionType: GreenActionType;
  karmaEarned?: number;
  ward?: string;
  verified?: boolean;
}

/**
 * Record a green action and update scores.
 */
export async function addGreenAction(userId: string, params: GreenActionParams) {
  const { Types } = require('mongoose');
  const { actionType, karmaEarned = 0, ward = '', verified = false } = params;
  const userOid = new Types.ObjectId(userId);

  let profile = await GreenScoreProfile.findOne({ userId: userOid });
  if (!profile) {
    profile = await GreenScoreProfile.create({ userId: userOid });
  }

  // Add action to history
  profile.actionHistory.push({
    actionType,
    performedAt: new Date(),
    karmaEarned,
    ward,
    verified,
  });

  // Update category points
  const categoryMap: Record<GreenActionType, 'treePoints' | 'waterPoints' | 'wastePoints' | 'energyPoints'> = {
    tree_adoption: 'treePoints',
    sapling_planting: 'treePoints',
    lake_cleanup: 'waterPoints',
    water_conservation: 'waterPoints',
    waste_segregation: 'wastePoints',
    plastic_cleanup: 'wastePoints',
    composting: 'wastePoints',
    energy_saving: 'energyPoints',
  };

  const category = categoryMap[actionType];
  if (category) {
    (profile as unknown)[category] += verified ? 10 : 5;
  }

  profile.environmentalPoints += verified ? 10 : 5;
  profile.actionsPerformed += 1;
  profile.lastActionAt = new Date();
  profile.greenScore = profile.computeGreenScore();
  profile.greenBengaluruScore = profile.computeGreenBengaluruScore();
  profile.missionsCompleted = await countGreenMissions(userId);

  await profile.save();

  logger.info('[NBKC] Green action recorded', { userId, actionType, verified });
  return {
    greenScore: profile.greenScore,
    greenBengaluruScore: profile.greenBengaluruScore,
    environmentalPoints: profile.environmentalPoints,
  };
}

async function countGreenMissions(userId: string): Promise<number> {
  const { Types } = require('mongoose');
  return CivicMissionEnrollment.countDocuments({
    userId: new Types.ObjectId(userId),
    completedAt: { $exists: true },
  });
}

function mapMissionToGreenAction(category: string): GreenActionType {
  const map: Record<string, GreenActionType> = {
    environment: 'tree_adoption',
    water: 'lake_cleanup',
    waste: 'waste_segregation',
    civic: 'plastic_cleanup',
    community: 'sapling_planting',
  };
  return map[category] ?? 'plastic_cleanup';
}

// ─── Tier Management ────────────────────────────────────────────────────────

async function checkAndUpgradeMembership(userId: string) {
  const { Types } = require('mongoose');
  const membership = await NBKCMembership.findOne({ userId: new Types.ObjectId(userId) });
  if (!membership || !membership.isActive) return;

  const thresholds = NBKCMembership.getTierThresholds();
  let newTier: NBKCMembershipTier | null = null;

  const missions = membership.missionsCompleted ?? 0;
  const hours = membership.totalCivicHours ?? 0;

  if (
    membership.tier === 'citizen' &&
    missions >= thresholds.active.missionsCompleted &&
    hours >= thresholds.active.totalCivicHours
  ) {
    newTier = 'active';
  } else if (
    membership.tier === 'active' &&
    missions >= thresholds.civic_leader.missionsCompleted &&
    hours >= thresholds.civic_leader.totalCivicHours
  ) {
    newTier = 'civic_leader';
  } else if (
    membership.tier === 'civic_leader' &&
    missions >= thresholds.ambassador.missionsCompleted &&
    hours >= thresholds.ambassador.totalCivicHours
  ) {
    newTier = 'ambassador';
  }

  if (newTier) {
    membership.tier = newTier;
    await membership.save();

    await sendToUser(userId, {
      title: 'NBKC Tier Upgraded!',
      body: `You've been promoted to ${newTier.replace('_', ' ')} tier!`,
      data: { type: 'nbkc_tier_upgrade', tier: newTier },
    });

    logger.info('[NBKC] Member upgraded', { userId, newTier });
  }

  // Check sticker eligibility
  if (membership.isEligibleForSticker() && membership.hasVehicle) {
    membership.stickerIssued = true;
    membership.stickerIssuedAt = new Date();
    await membership.save();

    await sendToUser(userId, {
      title: 'Your NBKC Sticker is Ready!',
      body: 'Visit the BBMP office to collect your vehicle sticker.',
      data: { type: 'nbkc_sticker_ready' },
    });
  }
}

// ─── Badges ──────────────────────────────────────────────────────────────────

async function checkNBKCBadges(userId: string, mission: ICivicMission) {
  const { Types } = require('mongoose');
  const membership = await NBKCMembership.findOne({ userId: new Types.ObjectId(userId) });
  const karmaProfile = await KarmaProfile.findOne({ userId: new Types.ObjectId(userId) });
  if (!karmaProfile) return;

  const earnedIds = new Set(karmaProfile.badges.map((b: IBadge) => b.id));
  const now = new Date();

  const badgeMissions = membership?.missionsCompleted ?? 0;
  const badgeHours = membership?.totalCivicHours ?? 0;

  const badgeDefs = [
    {
      id: 'lake_guardian',
      condition: badgeMissions >= 3 && mission.category === 'water',
      name: 'Lake Guardian',
    },
    {
      id: 'tree_steward',
      condition: badgeMissions >= 5 && mission.category === 'environment',
      name: 'Tree Steward',
    },
    {
      id: 'ward_champion',
      condition: badgeMissions >= 10,
      name: 'Ward Champion',
    },
    {
      id: 'civic_sentinel',
      condition: badgeHours >= 20,
      name: 'Civic Sentinel',
    },
    {
      id: 'green_ambassador',
      condition: membership?.tier === 'ambassador',
      name: 'Green Ambassador',
    },
  ];

  for (const def of badgeDefs) {
    if (!earnedIds.has(def.id) && def.condition) {
      karmaProfile.badges.push({ id: def.id, name: def.name, earnedAt: now });
      await karmaProfile.save();

      await emitKarmaAwardedEvent({
        userId,
        karmaAmount: 0,
        eventId: def.id,
        eventType: 'badge_earned',
        source: 'nbkc',
      });

      await sendToUser(userId, {
        title: 'Badge Earned!',
        body: `You earned the "${def.name}" badge!`,
        data: { type: 'badge_earned', badgeId: def.id },
      });

      logger.info('[NBKC] Badge awarded', { userId, badgeId: def.id });
    }
  }
}

// ─── Leaderboard ──────────────────────────────────────────────────────────────

/**
 * Get NBKC ward leaderboard.
 */
export async function getWardLeaderboard(ward: string, limit = 20) {
  const { Types } = require('mongoose');
  const members = await NBKCMembership.aggregate([
    { $match: { ward, isActive: true } },
    { $sort: { totalCivicHours: -1 } },
    { $limit: limit },
    {
      $lookup: {
        from: 'green_score_profiles',
        localField: 'userId',
        foreignField: 'userId',
        as: 'greenProfile',
      },
    },
    {
      $project: {
        userId: 1,
        memberNumber: 1,
        tier: 1,
        totalCivicHours: 1,
        missionsCompleted: 1,
        greenBengaluruScore: { $arrayElemAt: ['$greenProfile.greenBengaluruScore', 0] },
      },
    },
  ]);

  return members.map((m, i) => ({ rank: i + 1, ...m }));
}

/**
 * Get global NBKC leaderboard.
 */
export async function getGlobalLeaderboard(limit = 20) {
  const { Types } = require('mongoose');
  const members = await NBKCMembership.aggregate([
    { $match: { isActive: true } },
    { $sort: { totalCivicHours: -1 } },
    { $limit: limit },
    {
      $lookup: {
        from: 'green_score_profiles',
        localField: 'userId',
        foreignField: 'userId',
        as: 'greenProfile',
      },
    },
    {
      $project: {
        userId: 1,
        memberNumber: 1,
        tier: 1,
        totalCivicHours: 1,
        missionsCompleted: 1,
        greenBengaluruScore: { $arrayElemAt: ['$greenProfile.greenBengaluruScore', 0] },
      },
    },
  ]);

  return members.map((m, i) => ({ rank: i + 1, ...m }));
}
