apiVersion: v1
kind: Service
metadata:
  name: fitmind
  namespace: hojai
  labels:
    app: fitmind
    company: hojai-ai
    industry: fitness
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4801
      protocol: TCP
      name: http
  selector:
    app: fitmind