apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ad-bazaar-social-publisher
  labels:
    app: ad-bazaar-social-publisher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ad-bazaar-social-publisher
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80