# Kubernetes Service for REZ-kds-mobile
apiVersion: v1
kind: Service
metadata:
  name: REZ-kds-mobile
  namespace: rez-merchant
  labels:
    app: REZ-kds-mobile
    managed-by: rez-merchant
  annotations:
    description: "REZ-kds-mobile service"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: REZ-kds-mobile
