// Mock data for dashboard demo
// In production, this would fetch from REZ-b2b-gateway

export const mockPipelineData = {
  totalValue: 2450000,
  weightedValue: 1837500,
  totalDeals: 47,
  winRate: 32,
  stages: [
    { name: 'Qualified', deals: 15, value: 450000, percentage: 18, color: '#3b82f6' },
    { name: 'Discovery', deals: 12, value: 520000, percentage: 21, color: '#8b5cf6' },
    { name: 'Proposal', deals: 10, value: 680000, percentage: 28, color: '#f59e0b' },
    { name: 'Negotiation', deals: 6, value: 450000, percentage: 18, color: '#ef4444' },
    { name: 'Closed Won', deals: 4, value: 350000, percentage: 15, color: '#22c55e' },
  ],
};

export const mockDealActivities = {
  deals: [
    {
      id: 'deal-1',
      name: 'Enterprise License',
      company: 'Acme Corp',
      value: 120000,
      stage: 'Negotiation',
      score: 85,
      priority: 'high',
      closeDate: '2026-06-15',
      nextAction: 'Send revised proposal',
    },
    {
      id: 'deal-2',
      name: 'Professional Plan',
      company: 'TechStart Inc',
      value: 48000,
      stage: 'Proposal',
      score: 72,
      priority: 'medium',
      closeDate: '2026-06-20',
      nextAction: 'Schedule demo call',
    },
    {
      id: 'deal-3',
      name: 'Starter Package',
      company: 'LocalShop',
      value: 12000,
      stage: 'Discovery',
      score: 45,
      priority: 'low',
      closeDate: '2026-07-01',
      nextAction: 'Follow up on questions',
    },
    {
      id: 'deal-4',
      name: 'Enterprise Plus',
      company: 'GlobalTech',
      value: 240000,
      stage: 'Qualified',
      score: 60,
      priority: 'high',
      closeDate: '2026-07-15',
      nextAction: 'Initial discovery call',
    },
    {
      id: 'deal-5',
      name: 'Growth Plan',
      company: 'ScaleUp Co',
      value: 72000,
      stage: 'Closed Won',
      score: 95,
      priority: 'medium',
      closeDate: '2026-05-30',
      nextAction: 'Kickoff meeting scheduled',
    },
  ],
  activities: [
    {
      id: 'act-1',
      type: 'email',
      title: 'Sent proposal to Acme Corp',
      user: 'John Smith',
      time: '2 hours ago',
    },
    {
      id: 'act-2',
      type: 'call',
      title: 'Discovery call with TechStart',
      user: 'Sarah Johnson',
      time: '4 hours ago',
    },
    {
      id: 'act-3',
      type: 'meeting',
      title: 'Demo completed for GlobalTech',
      user: 'Mike Wilson',
      time: 'Yesterday',
    },
    {
      id: 'act-4',
      type: 'linkedin',
      title: 'Connected with CTO at ScaleUp',
      user: 'John Smith',
      time: 'Yesterday',
    },
    {
      id: 'act-5',
      type: 'note',
      title: 'Updated deal notes for LocalShop',
      user: 'Sarah Johnson',
      time: '2 days ago',
    },
  ],
};

export const mockSignals = [
  {
    id: 'sig-1',
    type: 'funding',
    title: '$50M Series C Raised',
    company: 'Acme Corp',
    intent: 'high',
    date: '2026-06-01',
    description: 'Recent funding indicates budget for enterprise tools',
  },
  {
    id: 'sig-2',
    type: 'expansion',
    title: 'Opened 3 New Offices',
    company: 'TechStart Inc',
    intent: 'high',
    date: '2026-05-28',
    description: 'Expansion signals need for collaboration tools',
  },
  {
    id: 'sig-3',
    type: 'news',
    title: 'Featured in TechCrunch',
    company: 'GlobalTech',
    intent: 'medium',
    date: '2026-05-25',
    description: 'Positive press coverage indicates growth trajectory',
  },
  {
    id: 'sig-4',
    type: 'job_posting',
    title: 'Hiring 10 Sales Reps',
    company: 'ScaleUp Co',
    intent: 'medium',
    date: '2026-05-20',
    description: 'Hiring spree suggests revenue focus',
  },
  {
    id: 'sig-5',
    type: 'executive_change',
    title: 'New VP of Sales Appointed',
    company: 'LocalShop',
    intent: 'low',
    date: '2026-05-18',
    description: 'Leadership change may open buying window',
  },
  {
    id: 'sig-6',
    type: 'partnership',
    title: 'Partnered with AWS',
    company: 'CloudFirst',
    intent: 'high',
    date: '2026-06-02',
    description: 'Partnership indicates scale and budget',
  },
];

export const mockForecast = {
  actual: [
    { month: 'Jan', value: 180 },
    { month: 'Feb', value: 220 },
    { month: 'Mar', value: 195 },
    { month: 'Apr', value: 280 },
    { month: 'May', value: 310 },
    { month: 'Jun', value: 0 },
  ],
  forecast: [
    { month: 'Jan', value: 0 },
    { month: 'Feb', value: 0 },
    { month: 'Mar', value: 0 },
    { month: 'Apr', value: 0 },
    { month: 'May', value: 0 },
    { month: 'Jun', value: 350 },
  ],
  target: [
    { month: 'Jan', value: 200 },
    { month: 'Feb', value: 200 },
    { month: 'Mar', value: 250 },
    { month: 'Apr', value: 250 },
    { month: 'May', value: 300 },
    { month: 'Jun', value: 350 },
  ],
};
