import { IAgreement } from '../models/agreement.model.js';
import { config } from '../config/index.js';

export interface NOCData {
  agreement: IAgreement;
  company: {
    name: string;
    address: string;
    phone: string;
    email: string;
    website: string;
  };
  agreementDateFormatted: string;
  propertyAddressFormatted: string;
}

export const nocTemplate = {
  /**
   * Format date in Indian format
   */
  formatDate: (date: Date | string): string => {
    const d = new Date(date);
    return d.toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric'
    });
  },

  /**
   * Prepare template data
   */
  prepareData: (agreement: IAgreement): NOCData => {
    return {
      agreement,
      company: {
        name: config.company.name,
        address: config.company.address,
        phone: config.company.phone,
        email: config.company.email,
        website: config.company.website
      },
      agreementDateFormatted: nocTemplate.formatDate(agreement.agreementDate),
      propertyAddressFormatted: agreement.propertyAddress
    };
  },

  /**
   * Get default conditions for NOC
   */
  getDefaultConditions: (): string[] => {
    return [
      'This No Objection Certificate is issued to confirm that we have no objection to the transaction/procedure mentioned herein.',
      'We confirm that all outstanding dues, if any, related to the property have been cleared.',
      'We agree to cooperate fully in the completion of the transaction/procedure.',
      'This NOC is valid for a period of 90 days from the date of issue.',
      'We understand that this NOC does not absolve any legal obligations we may have.'
    ];
  },

  /**
   * Generate NOC text
   */
  generateText: (data: NOCData): string => {
    const { agreement } = data;

    let text = `
${data.company.name.toUpperCase()}
${data.company.address}
Phone: ${data.company.phone} | Email: ${data.company.email}

================================================================================
              NO OBJECTION CERTIFICATE (NOC)
================================================================================

Reference No: ${agreement.agreementId}
Date: ${data.agreementDateFormatted}

================================================================================

TO WHOM IT MAY CONCERN

This is to certify that ${agreement.sellerId} ("the Owner") is the owner/authorized
person of the property located at:

${data.propertyAddressFormatted}

Property Type: ${agreement.propertyType.charAt(0).toUpperCase() + agreement.propertyType.slice(1)}
Property Area: ${agreement.propertyArea} ${agreement.propertyAreaUnit.toUpperCase()}

================================================================================
                              CERTIFICATION
================================================================================

We hereby certify that:

1. We have NO OBJECTION to the proposed transaction/procedure involving the
   aforementioned property.

2. All outstanding dues, maintenance charges, property taxes, and other
   fees related to this property have been cleared up to this date.

3. The property is free from any legal disputes, encumbrances, or pending
   litigation.

4. We agree to provide all necessary cooperation and documentation required
   for the completion of this transaction.

5. We understand and agree that this No Objection Certificate is valid for
   a period of 90 days from the date of issue.

================================================================================
                              CONDITIONS
================================================================================
`;

    const conditions = nocTemplate.getDefaultConditions();
    conditions.forEach((condition, index) => {
      text += `\n${index + 1}. ${condition}`;
    });

    text += `
================================================================================
                              SIGNATURES
================================================================================

OWNER (Seller):
Signature: ${agreement.sellerSignature ? '[Signature on file]' : '_____________________________'}
Date: ${agreement.sellerSignedAt ? nocTemplate.formatDate(agreement.sellerSignedAt) : 'Pending'}

WITNESS 1:
Signature: ${agreement.witness1Signature ? '[Signature on file]' : '_____________________________'}
Date: ${agreement.witness1SignedAt ? nocTemplate.formatDate(agreement.witness1SignedAt) : 'Pending'}

WITNESS 2:
Signature: ${agreement.witness2Signature ? '[Signature on file]' : '_____________________________'}
Date: ${agreement.witness2SignedAt ? nocTemplate.formatDate(agreement.witness2SignedAt) : 'Pending'}

================================================================================
                    Generated by ${data.company.name} Agreement Service
================================================================================
`;

    return text;
  }
};

export default nocTemplate;