apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rtmn
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployments.yaml
  - services.yaml
  - statefulsets.yaml
  - ingress.yaml
  - hpa.yaml
commonLabels:
  managed-by: kustomize
  rtmn.io/part-of: rtmn-platform