apiVersion: v1
kind: Namespace
metadata:
  name: rtmn
  labels:
    name: rtmn
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: rtmn-monitoring
  labels:
    name: rtmn-monitoring
