apiVersion: v1
kind: Service
metadata:
  name: ad-bazaar-brand-partnership
  namespace: adbazaar
  labels:
    app: ad-bazaar-brand-partnership
    tier: social-automation
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5112"
spec:
  type: ClusterIP
  ports:
  - port: 5112
    targetPort: 5112
    protocol: TCP
    name: http
  selector:
    app: ad-bazaar-brand-partnership