# Kubernetes Service for rez-supplier-marketplace
apiVersion: v1
kind: Service
metadata:
  name: rez-supplier-marketplace
  namespace: rez-merchant
  labels:
    app: rez-supplier-marketplace
    managed-by: rez-merchant
  annotations:
    description: "rez-supplier-marketplace service"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4630
      targetPort: http
      protocol: TCP
  selector:
    app: rez-supplier-marketplace
