apiVersion: v1
kind: Service
metadata:
  name: ad-bazaar-ugc-management
  namespace: adbazaar
  labels:
    app: ad-bazaar-ugc-management
    tier: social-automation
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5101"
spec:
  type: ClusterIP
  ports:
  - port: 5101
    targetPort: 5101
    protocol: TCP
    name: http
  selector:
    app: ad-bazaar-ugc-management