"""
AssetMind Report Generator
Port: 5302

Generates investment reports in multiple formats: PDF, Excel, HTML.
Creates portfolio reports, due diligence reports, and analyst notes.
"""

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
import json
import base64
import io


app = FastAPI(title="AssetMind Report Generator", version="1.0.0")


class ReportType(str, Enum):
    PORTFOLIO_SUMMARY = "portfolio_summary"
    DUE_DILIGENCE = "due_diligence"
    INVESTMENT_MEMO = "investment_memo"
    RISK_REPORT = "risk_report"
    PERFORMANCE_REPORT = "performance_report"
    ANALYST_NOTE = "analyst_note"


class ReportFormat(str, Enum):
    PDF = "pdf"
    EXCEL = "excel"
    HTML = "html"
    JSON = "json"


class Section(BaseModel):
    title: str
    content: str
    data: Optional[Dict] = None
    chart_type: Optional[str] = None


class ReportRequest(BaseModel):
    report_type: ReportType
    title: str
    subtitle: Optional[str] = None
    sections: List[Section]
    format: ReportFormat = ReportFormat.PDF
    include_header: bool = True
    include_footer: bool = True


class GeneratedReport(BaseModel):
    report_id: str
    title: str
    report_type: str
    format: str
    created_at: str
    file_size: int
    content_base64: Optional[str] = None
    download_url: Optional[str] = None


def generate_html_report(report: ReportRequest) -> str:
    """Generate HTML report."""
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{report.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
        h1 {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; }}
        h2 {{ color: #303f9f; margin-top: 30px; }}
        .header {{ background: #e8eaf6; padding: 20px; border-radius: 8px; margin-bottom: 30px; }}
        .section {{ margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 5px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #c5cae9; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{report.title}</h1>
        {f'<p>{report.subtitle}</p>' if report.subtitle else ''}
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    </div>
"""

    for section in report.sections:
        html += f"""
    <div class="section">
        <h2>{section.title}</h2>
        <p>{section.content}</p>
"""
        if section.data:
            if isinstance(section.data, list):
                html += "<table><tr>"
                if section.data and isinstance(section.data[0], dict):
                    for key in section.data[0].keys():
                        html += f"<th>{key}</th>"
                    html += "</tr>"
                    for row in section.data:
                        html += "<tr>"
                        for val in row.values():
                            html += f"<td>{val}</td>"
                        html += "</tr>"
                html += "</table>"
            elif isinstance(section.data, dict):
                html += "<table>"
                for key, val in section.data.items():
                    html += f"<tr><th>{key}</th><td>{val}</td></tr>"
                html += "</table>"
        html += "</div>"

    html += f"""
    <div class="footer">
        <p>Generated by AssetMind Platform | Confidential</p>
    </div>
</body>
</html>
"""
    return html


def generate_excel_content(report: ReportRequest) -> Dict[str, Any]:
    """Generate Excel-compatible JSON structure."""
    sheets = {}

    # Summary sheet
    summary_data = [["Report", report.title], ["Type", report.report_type.value], ["Generated", datetime.now().isoformat()]]
    sheets["Summary"] = summary_data

    # Section sheets
    for i, section in enumerate(report.sections):
        sheet_name = f"Section_{i+1}" if len(section.title) > 31 else section.title[:31]
        data = [[section.title], [section.content]]

        if section.data:
            if isinstance(section.data, list) and section.data:
                if isinstance(section.data[0], dict):
                    headers = list(section.data[0].keys())
                    data.append(headers)
                    for row in section.data:
                        data.append(list(row.values()))
                else:
                    data.append(section.data)
            elif isinstance(section.data, dict):
                for key, val in section.data.items():
                    data.append([key, val])

        sheets[sheet_name] = data

    return {"sheets": sheets}


def generate_pdf_content(report: ReportRequest) -> bytes:
    """Generate PDF (simplified - returns HTML for now, actual PDF needs reportlab)."""
    html = generate_html_report(report)
    return html.encode('utf-8')


@app.get("/health")
async def health():
    return {"status": "healthy", "service": "report-generator", "version": "1.0.0"}


@app.post("/generate", response_model=GeneratedReport)
async def generate_report(request: ReportRequest):
    """Generate an investment report."""

    report_id = f"rpt-{datetime.now().timestamp()}"

    if request.format == ReportFormat.HTML:
        content = generate_html_report(request)
        content_base64 = base64.b64encode(content.encode()).decode()
        file_size = len(content.encode())
    elif request.format == ReportFormat.EXCEL:
        content = generate_excel_content(request)
        content_base64 = base64.b64encode(json.dumps(content).encode()).decode()
        file_size = len(json.dumps(content).encode())
    elif request.format == ReportFormat.PDF:
        content = generate_pdf_content(request)
        content_base64 = base64.b64encode(content).decode()
        file_size = len(content)
    else:
        content = {"report": request.dict()}
        content_base64 = base64.b64encode(json.dumps(content).encode()).decode()
        file_size = len(json.dumps(content).encode())

    return GeneratedReport(
        report_id=report_id,
        title=request.title,
        report_type=request.report_type.value,
        format=request.format.value,
        created_at=datetime.now().isoformat(),
        file_size=file_size,
        content_base64=content_base64,
        download_url=f"/reports/{report_id}/download"
    )


@app.post("/generate/portfolio-summary")
async def generate_portfolio_summary(
    portfolio_name: str,
    total_value: float,
    day_pnl: float,
    positions: List[Dict]
):
    """Generate portfolio summary report."""
    sections = [
        Section(
            title="Portfolio Overview",
            content=f"Total portfolio value: ${total_value:,.2f}",
            data={"Portfolio": portfolio_name, "Total Value": f"${total_value:,.2f}"}
        ),
        Section(
            title="Daily Performance",
            content=f"Day P&L: ${day_pnl:,.2f} ({day_pnl/total_value*100:.2f}%)",
            data={"P&L": f"${day_pnl:,.2f}", "Return": f"{day_pnl/total_value*100:.2f}%"}
        ),
        Section(
            title="Top Holdings",
            content="Current positions",
            data=positions[:10] if len(positions) > 10 else positions
        )
    ]

    request = ReportRequest(
        report_type=ReportType.PORTFOLIO_SUMMARY,
        title=f"Portfolio Summary: {portfolio_name}",
        subtitle=datetime.now().strftime("%B %d, %Y"),
        sections=sections,
        format=ReportFormat.HTML
    )

    return await generate_report(request)


@app.post("/generate/risk-report")
async def generate_risk_report(
    portfolio_name: str,
    var_95: float,
    cvar_95: float,
    max_drawdown: float,
    volatility: float,
    risk_factors: List[Dict]
):
    """Generate risk report."""
    sections = [
        Section(
            title="Risk Metrics",
            content="Key risk indicators",
            data={
                "VaR (95%)": f"${var_95:,.2f}",
                "CVaR (95%)": f"${cvar_95:,.2f}",
                "Max Drawdown": f"{max_drawdown:.2f}%",
                "Volatility": f"{volatility:.2f}%"
            }
        ),
        Section(
            title="Risk Factors",
            content="Top risk contributors",
            data=risk_factors
        )
    ]

    request = ReportRequest(
        report_type=ReportType.RISK_REPORT,
        title=f"Risk Report: {portfolio_name}",
        subtitle=datetime.now().strftime("%B %d, %Y"),
        sections=sections,
        format=ReportFormat.HTML
    )

    return await generate_report(request)


@app.get("/templates")
async def list_templates():
    """List available report templates."""
    return {
        "templates": [
            {"type": "portfolio_summary", "name": "Portfolio Summary", "sections": ["Overview", "Performance", "Holdings"]},
            {"type": "due_diligence", "name": "Due Diligence Report", "sections": ["Company", "Financials", "Risks", "Recommendation"]},
            {"type": "risk_report", "name": "Risk Report", "sections": ["Metrics", "Factors", "Recommendations"]},
            {"type": "performance_report", "name": "Performance Report", "sections": ["Returns", "Attribution", "Benchmark"]},
            {"type": "analyst_note", "name": "Analyst Note", "sections": ["Summary", "Analysis", "Action"]}
        ]
    }


@app.get("/reports/{report_id}/download")
async def download_report(report_id: str, format: str = "html"):
    """Download a generated report."""
    return {"report_id": report_id, "message": "Report download endpoint", "format": format}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5302)