import { MediaItem } from './types';
import { v4 as uuidv4 } from 'uuid';

const now = new Date().toISOString();

// Realistic mock media data for advertising/advertisement use cases
export const mockMediaItems: MediaItem[] = [
  {
    id: uuidv4(),
    filename: 'hero-banner-1920x600.jpg',
    originalFilename: 'hero-banner-1920x600.jpg',
    mimeType: 'image/jpeg',
    size: 245760,
    width: 1920,
    height: 600,
    url: 'https://cdn.adbazaar.com/media/hero-banner-1920x600.jpg',
    thumbnailUrl: 'https://cdn.adbazaar.com/media/thumbs/hero-banner-1920x600.jpg',
    metadata: {
      format: 'JPEG',
      colorspace: 'sRGB',
      hasAlpha: false,
      orientation: 1,
    },
    transformations: [
      {
        id: uuidv4(),
        type: 'resize',
        params: { width: 768, height: 240, fit: 'cover' },
        resultUrl: 'https://cdn.adbazaar.com/media/hero-banner-768x240.jpg',
        createdAt: now,
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'ready',
    tags: ['hero', 'banner', 'homepage', 'promotional'],
  },
  {
    id: uuidv4(),
    filename: 'product-showcase-1080p.mp4',
    originalFilename: 'product-showcase-1080p.mp4',
    mimeType: 'video/mp4',
    size: 15728640,
    width: 1920,
    height: 1080,
    url: 'https://cdn.adbazaar.com/media/product-showcase-1080p.mp4',
    thumbnailUrl: 'https://cdn.adbazaar.com/media/thumbs/product-showcase-1080p.jpg',
    metadata: {
      format: 'MP4',
      duration: 45,
      bitrate: 2800000,
      colorspace: 'yuv420p',
    },
    transformations: [
      {
        id: uuidv4(),
        type: 'compress',
        params: { quality: 0.8, preset: 'medium' },
        resultUrl: 'https://cdn.adbazaar.com/media/product-showcase-720p.mp4',
        createdAt: now,
      },
    ],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'ready',
    tags: ['video', 'product', 'showcase', 'showroom'],
  },
  {
    id: uuidv4(),
    filename: 'brand-logo-transparent.png',
    originalFilename: 'brand-logo-transparent.png',
    mimeType: 'image/png',
    size: 51200,
    width: 512,
    height: 512,
    url: 'https://cdn.adbazaar.com/media/brand-logo-transparent.png',
    thumbnailUrl: 'https://cdn.adbazaar.com/media/thumbs/brand-logo-transparent.png',
    metadata: {
      format: 'PNG',
      colorspace: 'RGBA',
      hasAlpha: true,
      orientation: 1,
    },
    transformations: [],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'ready',
    tags: ['logo', 'brand', 'transparent', 'vector-like'],
  },
  {
    id: uuidv4(),
    filename: 'testimonial-cta-banner.jpg',
    originalFilename: 'testimonial-cta-banner.jpg',
    mimeType: 'image/jpeg',
    size: 184320,
    width: 1200,
    height: 400,
    url: 'https://cdn.adbazaar.com/media/testimonial-cta-banner.jpg',
    thumbnailUrl: 'https://cdn.adbazaar.com/media/thumbs/testimonial-cta-banner.jpg',
    metadata: {
      format: 'JPEG',
      colorspace: 'sRGB',
      hasAlpha: false,
      orientation: 1,
      exif: {
        camera: 'Canon EOS R5',
        lens: '24-70mm f/2.8',
        iso: 100,
      },
    },
    transformations: [
      {
        id: uuidv4(),
        type: 'grayscale',
        params: {},
        resultUrl: 'https://cdn.adbazaar.com/media/testimonial-cta-banner-bw.jpg',
        createdAt: now,
      },
      {
        id: uuidv4(),
        type: 'resize',
        params: { width: 600, height: 200, fit: 'contain' },
        resultUrl: 'https://cdn.adbazaar.com/media/testimonial-cta-banner-600.jpg',
        createdAt: now,
      },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'ready',
    tags: ['testimonial', 'cta', 'banner', 'conversion'],
  },
  {
    id: uuidv4(),
    filename: 'social-media-square.jpg',
    originalFilename: 'social-media-square.jpg',
    mimeType: 'image/jpeg',
    size: 102400,
    width: 1080,
    height: 1080,
    url: 'https://cdn.adbazaar.com/media/social-media-square.jpg',
    thumbnailUrl: 'https://cdn.adbazaar.com/media/thumbs/social-media-square.jpg',
    metadata: {
      format: 'JPEG',
      colorspace: 'sRGB',
      hasAlpha: false,
      orientation: 1,
    },
    transformations: [
      {
        id: uuidv4(),
        type: 'crop',
        params: { width: 1080, height: 1080, x: 0, y: 0 },
        resultUrl: 'https://cdn.adbazaar.com/media/social-media-square-cropped.jpg',
        createdAt: now,
      },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'ready',
    tags: ['social', 'instagram', 'square', 'social-media'],
  },
];
